// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsWfXX4jvePOaUAwOx0kN7Yk9QDtkPO1Y',
    appId: '1:1007800094469:web:2588b949a6bd10d608316c',
    messagingSenderId: '1007800094469',
    projectId: 'instagram-clone-bd970',
    authDomain: 'instagram-clone-bd970.firebaseapp.com',
    storageBucket: 'instagram-clone-bd970.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo_Axlo23cAY5nnEaTZpCTX0gxCsOueX0',
    appId: '1:1007800094469:android:c1aa6187ec61c6e608316c',
    messagingSenderId: '1007800094469',
    projectId: 'instagram-clone-bd970',
    storageBucket: 'instagram-clone-bd970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxuUVpW-R9MPeunnLkO37NnigdviR8zzw',
    appId: '1:1007800094469:ios:f30b0a431cec5c8e08316c',
    messagingSenderId: '1007800094469',
    projectId: 'instagram-clone-bd970',
    storageBucket: 'instagram-clone-bd970.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

}